/* KPSS 2026 — Çalışma Motoru: akıllı hedef, odak döngüsü, tekrar kuyruğu, başarılar */
(function(){
'use strict';
const KEY='kpss_focus_hub_v2';
const defaults=()=>({sessions:[],achievements:{},focus:{minutes:25,break:5},profile:'Ahmet'});
let HUB={...defaults(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})};
HUB.sessions=Array.isArray(HUB.sessions)?HUB.sessions:[];HUB.achievements=HUB.achievements||{};HUB.focus={...defaults().focus,...(HUB.focus||{})};
const save=()=>localStorage.setItem(KEY,JSON.stringify(HUB));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>bugunStr();
function allTopics(){return typeof calismaKonulariniGetir==='function'?calismaKonulariniGetir():[];}
function weakTopics(){return allTopics().filter(k=>(k.soru||0)>=3).sort((a,b)=>((b.yanlis||0)/Math.max(1,b.soru||0))-((a.yanlis||0)/Math.max(1,a.soru||0))).slice(0,5);}
function reviewTopics(){return allTopics().filter(k=>k.durum==='tekrar'||((k.soru||0)>=5&&yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))<70)).sort((a,b)=>(a.durum==='tekrar'?0:1)-(b.durum==='tekrar'?0:1));}
function streak(){let n=0,d=new Date();while(n<365){const s=bugunStr(d),r=STATE.gunlukKayitlar[s];if(!r||(r.calismaDk<=0&&r.soru<=0))break;n++;d.setDate(d.getDate()-1);}return n;}
function todaySessions(){return HUB.sessions.filter(x=>x.date===today());}
function addAchievement(id,label){if(HUB.achievements[id])return;HUB.achievements[id]={date:today(),label};save();toast('🏆 '+label);}
function checkAchievements(){const total=genelToplamSoru(),mins=genelToplamCalismaDk(),done=allTopics().filter(k=>k.durum==='tamamlandi').length;if(total>=100)addAchievement('100s','100 soru tamamlandı');if(total>=500)addAchievement('500s','500 soru tamamlandı');if(total>=1000)addAchievement('1000s','1000 soru tamamlandı');if(mins>=300)addAchievement('5h','Toplam 5 saat çalışma');if(mins>=1200)addAchievement('20h','Toplam 20 saat çalışma');if(streak()>=3)addAchievement('3day','3 günlük seri');if(streak()>=7)addAchievement('7day','7 günlük seri');if(done>=10)addAchievement('10topic','10 konu tamamlandı');if(done>=25)addAchievement('25topic','25 konu tamamlandı');}
function renderHub(){const page=document.querySelector('#page-calisma');if(!page)return;const review=reviewTopics(),weak=weakTopics(),g=gunlukKayitAl(),dk=g.calismaDk||0,soru=g.soru||0,hedefDk=STATE.ayarlar.gunlukCalismaHedefiDk||180,hedefSoru=STATE.ayarlar.gunlukSoruHedefi||80,focus=Math.min(100,Math.round(dk/Math.max(1,hedefDk)*100)),ach=Object.values(HUB.achievements).slice(-4).reverse(),missionDone=Math.min(1,Math.floor(dk/25))+Math.min(1,Math.floor(soru/20))+(todaySessions().length?1:0);const old=page.querySelector('.study-hero');if(!old)return;page.querySelectorAll('.focus-hub,.smart-study-grid').forEach(x=>x.remove());const anchor=page.querySelector('.study-quick-grid');const box=document.createElement('div');box.className='focus-hub';box.innerHTML=`<div class="focus-hub-main"><div class="focus-hub-kicker">⚡ BUGÜNÜN ÇALIŞMA MASASI</div><div class="focus-hub-title">${focus>=100?'Günün ana hedefi tamamlandı. Şimdi pekiştir.':'Bir oturum daha. Sonra sonucu birlikte göreceğiz.'}</div><div class="focus-bars"><div><span>⏱️ Çalışma <b>${dk}/${hedefDk} dk</b></span><i><em style="width:${Math.min(100,dk/hedefDk*100)}%"></em></i></div><div><span>📝 Soru <b>${soru}/${hedefSoru}</b></span><i><em style="width:${Math.min(100,soru/hedefSoru*100)}%"></em></i></div></div><div class="focus-actions"><button type="button" class="btn btn-primary" id="hubFocusBtn">⏱️ Odak oturumu başlat</button><button type="button" class="btn btn-outline" id="hubReviewBtn">🔁 Akıllı tekrar (${review.length})</button></div></div><div class="focus-hub-side"><div class="hub-stat"><strong>🔥 ${streak()}</strong><span>gün seri</span></div><div class="hub-stat"><strong>🎯 ${missionDone}/3</strong><span>mini görev</span></div><div class="hub-stat"><strong>⏱️ ${todaySessions().length}</strong><span>bugün oturum</span></div></div>`;anchor?.parentNode.insertBefore(box,anchor);box.querySelector('#hubFocusBtn')?.addEventListener('click',()=>openFocusModal());box.querySelector('#hubReviewBtn')?.addEventListener('click',openReviewModal);renderSmartPanels(page,weak,ach);}
function renderSmartPanels(page,weak,ach){const wrap=document.createElement('div');wrap.className='smart-study-grid';const weakHtml=weak.length?weak.map(k=>`<button type="button" class="smart-topic" data-hub-ders="${esc(k.dersId)}" data-hub-id="${esc(k.id)}"><span class="smart-dot" style="background:${k.renk}"></span><span><b>${esc(k.ad)}</b><small>${esc(k.ders)} · %${yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))} başarı</small></span><strong>Çalış →</strong></button>`).join(''):'<div class="smart-empty">Henüz yeterli soru verisi yok.</div>';const achHtml=ach.length?ach.map(a=>`<div class="achievement"><span>🏆</span><div><b>${esc(a.label)}</b><small>${esc(a.date)}</small></div></div>`).join(''):'<div class="smart-empty">İlk başarını kazanmak için bir odak oturumu başlat. 👊</div>';wrap.innerHTML=`<section class="smart-panel"><div class="smart-panel-head"><div><h2>🎯 Zayıf Noktaların</h2><span>En çok puan kazandırabilecek konular</span></div></div>${weakHtml}</section><section class="smart-panel"><div class="smart-panel-head"><div><h2>🏆 Başarılar</h2><span>İlerledikçe açılır</span></div></div>${achHtml}</section>`;const toolbar=page.querySelector('.study-toolbar');toolbar?.parentNode.insertBefore(wrap,toolbar);wrap.querySelectorAll('[data-hub-id]').forEach(b=>b.addEventListener('click',()=>studyKonuAc(b.dataset.hubDers,b.dataset.hubId)));}
function openReviewModal(){const list=reviewTopics().slice(0,8);modalAc('🔁 Akıllı Tekrar',`<div class="smart-modal-intro"><strong>Bugün en çok işine yarayacak tekrarlar</strong><p>Yanlış oranı yüksek ve tekrar gerekli işaretli konular öne alınır.</p></div><div class="review-list">${list.length?list.map((k,i)=>`<button type="button" class="review-item" data-review-ders="${esc(k.dersId)}" data-review-id="${esc(k.id)}"><span>${i+1}</span><div><b>${esc(k.ad)}</b><small>${esc(k.ders)} · ${k.soru||0} soru · %${yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))}</small></div><strong>Başla →</strong></button>`).join(''):'<div class="smart-empty">Şimdilik tekrar kuyruğun boş.</div>'}</div>`,'<button type="button" class="btn btn-primary" id="reviewClose">Tamam</button>');document.querySelector('#reviewClose')?.addEventListener('click',modalKapat);document.querySelectorAll('[data-review-id]').forEach(b=>b.addEventListener('click',()=>{modalKapat();studyKonuAc(b.dataset.reviewDers,b.dataset.reviewId)}));}
let timer={mode:'focus',active:false,remaining:0,total:0,startedAt:0,interval:null,topic:null};
function clearTimer(){if(timer.interval){clearInterval(timer.interval);timer.interval=null;}}
function openFocusModal(topic){clearTimer();const topics=allTopics().filter(k=>k.durum!=='tamamlandi');topic=topic||topics[Math.floor(Math.random()*Math.max(1,topics.length))];if(!topic)return toast('Önce bir konu seçelim.');const mins=Math.max(5,Number(HUB.focus.minutes)||25);timer={mode:'focus',active:false,remaining:mins*60,total:mins*60,startedAt:0,interval:null,topic};modalAc('⏱️ Odak Oturumu',`<div class="focus-timer-wrap"><div class="focus-timer-mode">ODAKLAN · ${esc(topic.ders)}</div><div class="focus-timer" id="hubTimer">${fmt(timer.remaining)}</div><div class="focus-topic">📖 ${esc(topic.ad)}</div><div class="focus-timer-track"><i id="hubTimerBar"></i></div><p class="focus-timer-note">${mins} dakika sadece bu konuya odaklan.</p></div>`,'<button type="button" class="btn btn-outline" id="hubTimerSkip">Bitir</button><button type="button" class="btn btn-primary" id="hubTimerToggle">▶ Başlat</button>');document.querySelector('#hubTimerToggle')?.addEventListener('click',toggleTimer);document.querySelector('#hubTimerSkip')?.addEventListener('click',()=>finishTimer(false));updateTimer();}
function fmt(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function toggleTimer(){if(timer.active){timer.active=false;clearTimer();updateTimer();document.querySelector('#hubTimerToggle').textContent='▶ Devam';return}timer.active=true;timer.startedAt=Date.now();clearTimer();timer.interval=setInterval(()=>{const elapsed=Math.floor((Date.now()-timer.startedAt)/1000);if(elapsed<=0)return;timer.remaining=Math.max(0,timer.remaining-elapsed);timer.startedAt+=elapsed*1000;updateTimer();if(timer.remaining<=0)finishTimer(true);},250);document.querySelector('#hubTimerToggle').textContent='⏸ Duraklat';}
function updateTimer(){const el=document.querySelector('#hubTimer');if(el)el.textContent=fmt(timer.remaining);const bar=document.querySelector('#hubTimerBar');if(bar)bar.style.width=`${Math.max(0,100-(timer.remaining/Math.max(1,timer.total)*100))}%`;}
function finishTimer(completed){clearTimer();timer.active=false;const elapsed=Math.max(0,Math.round((timer.total-timer.remaining)/60));if(elapsed>0&&timer.topic){const k=studyKonuBul(timer.topic.dersId,timer.topic.id);if(k)k.calismaDk=(k.calismaDk||0)+elapsed;const g=gunlukKayitAl();g.calismaDk=(g.calismaDk||0)+elapsed;STATE.calismaOturumlari=Array.isArray(STATE.calismaOturumlari)?STATE.calismaOturumlari:[];STATE.calismaOturumlari.push({id:Date.now().toString(36),tarih:today(),dersId:timer.topic.dersId,konuId:timer.topic.id,dakika:elapsed,tur:'odak'});stateKaydet();HUB.sessions.push({date:today(),minutes:elapsed,topic:timer.topic.ad});HUB.sessions=HUB.sessions.slice(-100);save();checkAchievements();}modalKapat();if(completed){toast(`🎉 ${elapsed} dakika tamamlandı!`);setTimeout(openBreakTimer,300)}else toast(elapsed?`${elapsed} dakikalık oturum kaydedildi.`:'Oturum iptal edildi.');if(typeof renderCalisma==='function')renderCalisma();}
function openBreakTimer(){clearTimer();const mins=Math.max(1,Number(HUB.focus.break)||5);timer={mode:'break',active:false,remaining:mins*60,total:mins*60,startedAt:0,interval:null,topic:null};modalAc('☕ Mola',`<div class="focus-timer-wrap"><div class="focus-timer-mode">MOLA · ${mins} DAKİKA</div><div class="focus-timer" id="hubTimer">${fmt(timer.remaining)}</div><p class="focus-timer-note">Ayağa kalk, su iç ve geri dön.</p></div>`,'<button type="button" class="btn btn-outline" id="hubBreakSkip">Geç</button><button type="button" class="btn btn-primary" id="hubBreakToggle">▶ Başlat</button>');document.querySelector('#hubBreakToggle')?.addEventListener('click',toggleBreak);document.querySelector('#hubBreakSkip')?.addEventListener('click',()=>{clearTimer();modalKapat();});}
function toggleBreak(){if(timer.active){timer.active=false;clearTimer();document.querySelector('#hubBreakToggle').textContent='▶ Devam';return}timer.active=true;timer.startedAt=Date.now();clearTimer();timer.interval=setInterval(()=>{const elapsed=Math.floor((Date.now()-timer.startedAt)/1000);if(elapsed<=0)return;timer.remaining=Math.max(0,timer.remaining-elapsed);timer.startedAt+=elapsed*1000;updateTimer();if(timer.remaining<=0){clearTimer();timer.active=false;modalKapat();toast('☀️ Mola bitti. Hazırsan bir oturum daha.');}},250);document.querySelector('#hubBreakToggle').textContent='⏸ Duraklat';}
function enhance(){if(typeof renderCalisma!=='function')return;if(renderCalisma.__hub)return;const original=renderCalisma;function wrapped(){original();renderHub();}wrapped.__hub=true;window.renderCalisma=wrapped;checkAchievements();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
