/* KPSS 2026 - TÜM DERSLER KONU ANLATIM KÜTÜPHANESİ
   Her konu: temel -> ayrıntı -> örnek/yöntem -> KPSS tuzağı.
   lesson.js'deki mevcut ayrıntılı içerikleri korur; eksik konuları tamamlar.
*/
(function () {
  const konu = (tanim, temel, yontem, tuzak) => ({
    tanim,
    adimlar: [
      { baslik: "Temeli öğren", metin: temel, ipucu: "Önce kavramı kendi cümlenle tekrar et." },
      { baslik: "Mantığını kur", metin: yontem, ipucu: "Kuralı ezberlemek yerine neden-sonuç ilişkisini kur." },
      { baslik: "KPSS örneği", metin: "Bu konudan soru çözerken önce verilenleri ayır, sonra ilgili kuralı uygula ve sonucun seçeneklerdeki karşılığını kontrol et.", ipucu: "Soruyu okumadan seçeneklere atlama." },
      { baslik: "KPSS tuzağı", metin: tuzak, ipucu: "Yanlış seçenekleri eleyerek doğruya git; tek kelimeye bakıp karar verme." }
    ]
  });

  const M = {
    "Temel Kavramlar": konu("Sayı kümeleri, işlem önceliği ve temel matematik kavramlarını öğren.", "Doğal, tam, rasyonel ve irrasyonel sayıların temel özelliklerini ayırt et. Tek-çift, pozitif-negatif ve ardışık sayı kavramlarını bil.", "İşlem önceliğinde parantez, üs, çarpma-bölme ve toplama-çıkarma sırasını uygula. Ardışık sayılarda ortak farkı kullan.", "0'ın pozitif veya negatif olmadığını; 1'in asal olmadığını unutma."),
    "Sayı Basamakları": konu("Bir sayının basamak, basamak değeri ve sayı değerini kullanmayı öğren.", "Birler, onlar, yüzler gibi basamakların değerleri 10'un kuvvetleriyle ilişkilidir. Rakam ile sayıyı birbirinden ayır.", "Basamaklardaki rakamları değişkenlerle göstererek sayı kur: örneğin iki basamaklı sayı 10a+b biçimindedir.", "Rakamların 0-9 arasında olması ile basamak değerinin aynı şey olmadığını unutma."),
    "Bölme ve Bölünebilme": konu("Sayıların belirli sayılara kalansız bölünüp bölünmediğini hızlıca belirlemeyi öğren.", "2, 3, 4, 5, 6, 8, 9 ve 10 için temel bölünebilme kurallarını bil.", "Büyük sayıyı uzun uzun bölmek yerine son basamakları veya rakamlar toplamını kullan.", "6 için hem 2'ye hem 3'e bölünebilmesi gerektiğini unutma."),
    "EBOB - EKOK": konu("Ortak bölen ve ortak kat kavramlarını kullanarak EBOB ve EKOK sorularını çöz.", "EBOB ortak bölenlerin en büyüğü, EKOK ortak katların en küçüğüdür.", "Asal çarpanlara ayır; EBOB'da ortak asal çarpanların küçük üslerini, EKOK'ta tüm asal çarpanların büyük üslerini kullan.", "İki pozitif sayı için EBOB × EKOK = sayıların çarpımı bağıntısını uygun sorularda kullan."),
    "Rasyonel Sayılar": konu("Kesir biçimindeki sayılarla karşılaştırma ve dört işlem yapmayı öğren.", "Pay ve paydanın anlamını, işaret kurallarını ve eşdeğer kesirleri öğren.", "Karşılaştırmada ortak payda veya çapraz çarpma kullan; işlemlerde payda eşitlemeyi unutma.", "Negatif kesirlerde büyük görünen mutlak değerin daha küçük sayı olabileceğini unutma."),
    "Basit Eşitsizlikler": konu("Bir değişkenin alabileceği değer aralığını eşitsizliklerle bul.", "<, >, ≤ ve ≥ sembollerinin anlamını bil.", "Her iki tarafa aynı sayı ekleyip çıkarabilirsin; negatif sayıyla çarpma veya bölmede eşitsizlik yönünü değiştir.", "Negatif sayıyla bölme/çarpma sonrası yön değiştirmeyi unutma."),
    "Mutlak Değer": konu("Bir sayının sıfıra olan uzaklığını ve mutlak değer denklemlerini öğren.", "|x|, x'in 0'a uzaklığıdır ve her zaman 0 veya pozitiftir.", "|x|=a için a≥0 ise x=a veya x=-a durumlarını kullan; eşitsizliklerde aralık mantığı kur.", "Mutlak değeri sadece işaret silme olarak düşünmek karmaşık eşitsizliklerde hata yaptırır."),
    "Üslü Sayılar": konu("Üslü ifadelerin kurallarını ve işlem kolaylıklarını öğren.", "Aynı tabanlı çarpımda üsler toplanır, bölmede çıkarılır; kuvvetin kuvvetinde üsler çarpılır.", "Önce tabanları mümkün olduğunca eşitle, sonra üs kurallarını uygula.", "Negatif üs sayının negatif olduğu anlamına gelmez; tersini ifade eder."),
    "Köklü Sayılar": konu("Köklü ifadeleri sadeleştirmeyi, çarpmayı ve bölmeyi öğren.", "Kök içindeki tam kare çarpanlar dışarı çıkarılabilir.", "Kök içini çarpanlarına ayır; tam kareleri dışarı çıkar ve benzer köklü terimleri birleştir.", "√(a+b) ifadesini √a+√b şeklinde ayırmak genel olarak yanlıştır."),
    "Çarpanlara Ayırma": konu("Cebirsel ifadeleri çarpanlarının çarpımı biçiminde yazmayı öğren.", "Ortak çarpan, iki kare farkı ve tam kare özdeşlikleri temel yöntemlerdir.", "Önce ortak çarpanı ara; sonra özdeşlikleri kontrol et.", "İşaretleri özellikle iki kare farkı ve tam karelerde dikkatle kontrol et."),
    "Oran - Orantı": konu("İki çokluğun birbirine göre ilişkisini oran ve orantıyla ifade et.", "Oran iki çokluğun bölümü; orantı iki oranın eşitliğidir.", "Doğru orantıda biri artarken diğeri aynı yönde, ters orantıda zıt yönde değişir.", "Doğru ve ters orantıyı ayırmadan çapraz çarpım yapmak hataya yol açar."),
    "Denklem Çözme": konu("Bir bilinmeyeni içeren eşitliklerden bilinmeyenin değerini bul.", "Eşitliğin iki tarafına aynı işlemi uygulamak denklemin dengesini korur.", "Parantezleri aç, benzer terimleri topla, bilinmeyenleri bir tarafa sabitleri diğer tarafa al.", "Paydalı denklemlerde payda ile çarpmadan önce paydanın sıfır olamayacağını kontrol et."),
    "Sayı Problemleri": konu("Günlük hayattaki sayı ilişkilerini bilinmeyenlerle modellemeyi öğren.", "Ardışık sayılar, tek-çift sayılar ve basamak ilişkileri değişkenlerle ifade edilir.", "Sorudaki bilinmeyeni tanımla, verilen ilişkiyi denklem olarak yaz ve sonucu koşulla kontrol et.", "Sonucun soruda istenen büyüklük mü yoksa ara değişken mi olduğunu kontrol et."),
    "Yaş Problemleri": konu("Bugünkü, geçmişteki ve gelecekteki yaş ilişkilerini denklemle çöz.", "Yaş farkı zaman geçse de değişmez; toplam yaş ise kişi sayısına göre değişir.", "Bir kişinin bugünkü yaşını x alıp geçmiş ve geleceği x±y ile göster.", "Yaş farkının değişmediğini unutma; 'kaç yıl sonra' ifadesini tüm kişilere uygula."),
    "Kesir Problemleri": konu("Bir bütünün kesirlerle verilen parçalarını ve ilişkilerini hesapla.", "Bütün 1 veya uygun bir değişken alınabilir; parçalar pay/payda oranıyla ifade edilir.", "Önce bütünü tanımla, sonra her parçayı aynı değişken üzerinden yaz ve toplamı kur.", "Pay ile paydayı ters yorumlamak en yaygın hatadır; 'bütünün kaçı' ifadesini dikkatle oku."),
    "Hareket Problemleri": konu("Yol, hız ve zaman arasındaki ilişkiyi kullan.", "Temel bağıntı yol = hız × zaman'dır.", "Aynı birimleri kullan; karşılaşma sorularında bağıl hız mantığını kur.", "Saat-km ve dakika-km/saat birimlerini karıştırma."),
    "İşçi - Havuz Problemleri": konu("İş yapma hızlarını birim zamanda yapılan iş üzerinden hesapla.", "Bir işin tamamını 1 kabul edip her işçinin birim zamandaki payını bul.", "Aynı yönde çalışan hızları topla; dolan havuz ve boşalan havuz gibi zıt işleri işaretlerle ayır.", "İşçi sayısı ile iş yapma hızını aynı şey sanma; kişi başı hız ayrıca verilmiş olabilir."),
    "Yüzde Problemleri": konu("Bir miktarın yüzdesini, yüzde değişimini ve ardışık değişimleri hesapla.", "%a, sayının a/100'ü demektir.", "Artışta eski değer × (1+a/100), azalışta ×(1-a/100) çarpanını kullan.", "Ardışık %10 artış ve %10 azalışın birbirini tamamen götürmediğini unutma."),
    "Kar - Zarar Problemleri": konu("Maliyet, satış fiyatı, kâr ve zarar arasındaki ilişkiyi öğren.", "Kâr = satış - maliyet; zarar = maliyet - satış.", "Yüzde kâr/zarar hangi değer üzerinden isteniyorsa paydayı ona göre seç.", "Kâr yüzdesinin çoğu soruda maliyet üzerinden verildiğini, ancak soru kökünü mutlaka kontrol et."),
    "Karışım Problemleri": konu("Farklı oranlardaki karışımlardan yeni karışım oluşturmayı öğren.", "Saf madde miktarı = toplam miktar × oran bağıntısını kullan.", "Her karışımın saf madde miktarını hesapla, toplam saf maddeyi toplam karışıma bağla.", "Yüzdeleri doğrudan toplamak yerine miktarlarla ağırlıklandır."),
    "Kümeler": konu("Eleman, alt küme, birleşim, kesişim ve fark işlemlerini öğren.", "Kümeler elemanlardan oluşur; ∪ birleşim, ∩ kesişim ve \"\\A\" fark anlamına gelir.", "Venn şeması çizerek ortak ve ayrı elemanları yerleştir.", "Boş kümenin her kümenin alt kümesi olduğunu unutma."),
    "Fonksiyonlar": konu("Bir kümenin elemanlarını başka bir kümenin elemanlarına belirli kuralla eşleyen fonksiyonları öğren.", "Tanım kümesi, değer kümesi ve görüntü kümesini ayırt et.", "f(x) verildiğinde x yerine istenen değeri yaz; bileşke ve ters fonksiyonda tanımları sırayla uygula.", "Her bağıntı fonksiyon değildir; tanım kümesindeki her elemanın tek görüntüsü olmalıdır."),
    "Permütasyon - Kombinasyon - Olasılık": konu("Sıralamanın önemli olduğu ve olmadığı seçimleri ayırt et.", "Permütasyonda sıra önemlidir; kombinasyonda sıra önemli değildir. Olasılık uygun durum/tüm durum oranıdır.", "Önce 'sıra önemli mi?' sorusunu sor; sonra P(n,r) veya C(n,r) mantığını seç.", "Kombinasyonla permütasyonu karıştırma; aynı kişiler farklı sıralanıyorsa sonuç değişir."),
    "Geometri: Temel Kavramlar": konu("Doğru, doğru parçası, açı ve temel geometrik ilişkileri öğren.", "Nokta, doğru, ışın, doğru parçası ve açı temel kavramlardır.", "Şekli temiz çiz, verilen açıları işaretle ve bütünler/tümler gibi ilişkileri kullan.", "Şeklin görsel oranına güvenme; verilen bilgiye göre işlem yap."),
    "Üçgenler": konu("Üçgenlerde açı, kenar ve alan ilişkilerini öğren.", "İç açılar toplamı 180°'dir. Üçgen eşitsizliği ve özel üçgenler temel araçlardır.", "Verilen açıları tamamla; kenar ilişkilerinde büyük açı karşısında büyük kenar olduğunu kullan.", "Dik üçgende Pisagor kullanmadan önce hangi kenarın hipotenüs olduğunu belirle."),
    "Çokgenler": konu("Çokgenlerde iç-dış açı ve köşegen ilişkilerini öğren.", "n kenarlı çokgenin iç açıları toplamı (n-2)×180°'dir.", "n'yi belirle, formülü uygula; düzgün çokgende açıları eşit paylaş.", "Dış açı toplamının her dışbükey çokgende 360° olduğunu unutma."),
    "Çember ve Daire": konu("Çemberde yarıçap, çap, yay, açı ve daire alanı ilişkilerini öğren.", "Çap = 2r, çevre = 2πr, alan = πr².", "Merkez açı-yay ve çevre açı ilişkilerini kullan; alan sorularında yarıçapı doğru belirle.", "Çevre ile alan formüllerini karıştırma."),
    "Analitik Geometri": konu("Koordinat düzleminde doğru, eğim ve uzaklık ilişkilerini öğren.", "Eğim değişimin dikey/yatay oranıdır. Nokta ve doğru denklemleri koordinatlarla ifade edilir.", "İki noktadan eğimi bul, gerekiyorsa doğru denklemini kur; uzaklıkta koordinat farklarını kullan.", "Dikey doğrunun eğiminin tanımsız olduğunu unutma."),
    "Katı Cisimler": konu("Prizma, küp, silindir, koni ve kürede alan-hacim ilişkilerini öğren.", "Hacim üç boyutlu uzayda kaplanan miktardır; temel formüller şekle göre değişir.", "Önce şekli tanı, ölçüleri aynı birime getir, sonra uygun alan veya hacim formülünü uygula.", "Alan birimi ile hacim birimini karıştırma; hacimde birim küp kullanılır.")
  };

  const T = {
    "İslamiyet Öncesi Türk Tarihi": konu("İslamiyet öncesi Türk topluluklarının devlet yapısını, kültürünü ve önemli özelliklerini öğren.", "Asya Hunları, Göktürkler ve Uygurlar başta olmak üzere Türk devletlerinin siyasi ve kültürel özelliklerini ayırt et.", "Kavramları devletlerle eşleştir: kut, kurultay, ikili teşkilat, onlu sistem ve yerleşik yaşam gibi ipuçlarını kullan.", "Türklerin tamamının aynı anda yerleşik veya göçebe olduğunu düşünme; dönem ve devlet farklılıklarını dikkate al."),
    "İlk Türk İslam Devletleri": konu("Türklerin İslamiyet'i kabulünden sonraki ilk devletlerini ve kültürel mirasını öğren.", "Karahanlılar, Gazneliler ve Büyük Selçukluların temel özelliklerini ve önemli eserlerini ayırt et.", "Devlet-eser-özellik eşleştirme tablosu oluştur; Türk-İslam kültüründeki değişimi takip et.", "Karahanlıların ilk Müslüman Türk devleti olarak anılması ile Gaznelilerin Türk olmayan unsurlarını karıştırma."),
    "Türkiye Selçuklu Tarihi": konu("Anadolu Selçuklu Devleti'nin kuruluşunu, ekonomik ve kültürel gelişmesini öğren.", "Anadolu'nun Türkleşmesi, ticaret yolları, kervansaraylar ve önemli savaşlar temel başlıklardır.", "Savaşları sonuçlarıyla ve hükümdarları icraatlarıyla eşleştir.", "Türkiye Selçuklularını Büyük Selçuklulardan ayır; Anadolu merkezli gelişmeleri ayrıca düşün."),
    "Osmanlı Kuruluş Dönemi": konu("Osmanlı Beyliği'nin devletleşmesini ve kuruluş dönemindeki siyasi genişlemeyi öğren.", "Osman Bey, Orhan Bey ve I. Murad dönemlerinin temel siyasi ve teşkilat gelişmelerini öğren.", "Beylikten devlete geçişi; ilk düzenli ordu, divan, başkent ve Balkan ilerleyişi gibi başlıklarla sırala.", "Bir kurumun ilk kez kurulduğu dönemi karıştırmamak için kronoloji oluştur."),
    "Osmanlı Yükselme Dönemi": konu("Osmanlı'nın merkezi güç haline geldiği dönemdeki fetih ve teşkilat gelişmelerini öğren.", "Fatih, II. Bayezid, Yavuz ve Kanuni dönemlerinin temel olaylarını ayırt et.", "Padişah-olay-fetih-sonuç eşleştirmesi yap; İstanbul'un fethi, Mısır ve Avrupa politikalarını sırala.", "Yükselme dönemini tek bir padişahla sınırlama; farklı hükümdarların farklı alanlardaki gelişmelerini ayır."),
    "Osmanlı Duraklama Dönemi": konu("17. yüzyıldaki siyasi, ekonomik ve askeri sorunları ve ıslahat arayışlarını öğren.", "İç isyanlar, mali sorunlar, ordu düzenindeki bozulmalar ve Avrupa'daki gelişmeler dönemin ana çerçevesidir.", "Sorun → sonuç → çözüm şeklinde çalış; ıslahatçıların önerilerini eşleştir.", "Duraklama dönemini devletin tamamen durduğu bir dönem olarak yorumlama; siyasi ve kültürel faaliyetler devam etmiştir."),
    "Osmanlı Gerileme Dönemi": konu("18. yüzyılda Avrupa karşısındaki değişimi ve Osmanlı ıslahatlarını öğren.", "Lale Devri, askeri ve teknik yenilikler, antlaşmalar ve Avrupa etkisi temel başlıklardır.", "Antlaşmaları kaybedilen/kazanılan bölgeler ve siyasi sonuçlarıyla eşleştir.", "Lale Devri'ni yalnızca eğlence dönemi olarak görme; matbaa ve kültürel yenilikleri de öğren."),
    "Osmanlı Dağılma Dönemi": konu("19. yüzyılda milliyetçilik, dış baskı ve reformlarla Osmanlı'nın çözülme sürecini öğren.", "Fransız İhtilali'nin milliyetçilik etkisi, Tanzimat, Islahat, Kanun-i Esasi ve meşrutiyetler temel konulardır.", "Islahatları kronolojik sıraya koy ve hangi sorunu çözmek için yapıldığını düşün.", "Tanzimat ile Islahat Fermanı'nın amaçlarını ve ilan biçimlerini birbirine karıştırma."),
    "Osmanlı Kültür ve Medeniyeti": konu("Osmanlı'nın yönetim, eğitim, hukuk, ekonomi ve toplum yapısını öğren.", "Divan, tımar, millet sistemi, vakıf, medrese ve lonca gibi kavramların işlevlerini bil.", "Her kavramı 'hangi alan + ne işe yarar?' şeklinde eşleştir.", "Tımarı özel mülkiyet sanma; devlet toprağının gelir düzeniyle ilgili bir sistemdir."),
    "XX. Yüzyıl Başlarında Osmanlı Devleti": konu("20. yüzyıl başındaki siyasi krizleri ve Osmanlı'nın son dönemini öğren.", "Trablusgarp, Balkan Savaşları ve siyasi gelişmeler I. Dünya Savaşı öncesi ortamı oluşturur.", "Savaşları neden-sonuç ve kaybedilen bölgelerle kronolojik sırala.", "Trablusgarp ile Balkan Savaşlarının cephe ve sonuçlarını karıştırma."),
    "I. Dünya Savaşı": konu("I. Dünya Savaşı'nın nedenlerini, cephelerini ve sonuçlarını öğren.", "İttifaklar, Osmanlı'nın savaşa girişi, önemli cepheler ve Mondros'a giden süreç temel çerçevedir.", "Cepheleri savunma/saldırı ve amaçlarına göre grupla; savaşın genel sonuçlarını Osmanlı açısından ayrıca çıkar.", "Çanakkale'nin savunma cephesi olduğunu ve Milli Mücadele'den önceki döneme ait olduğunu unutma."),
    "Milli Mücadele Hazırlık Dönemi": konu("Mondros'tan TBMM'nin açılışına kadar Milli Mücadele'nin örgütlenmesini öğren.", "Amasya Genelgesi, Erzurum ve Sivas Kongreleri, Misakımilli ve Temsil Heyeti temel dönüm noktalarıdır.", "Olayları kronolojik sıraya koy; her belgenin aldığı kararı ve ulusal egemenlik vurgusunu eşleştir.", "Kongrelerin toplanış amacı ile kararlarını birbirine karıştırma."),
    "Kurtuluş Savaşı Cepheleri": konu("Kurtuluş Savaşı'ndaki Doğu, Güney ve Batı cephelerinin özelliklerini öğren.", "Doğu Cephesi Ermenilere, Güney Cephesi işgallere karşı yerel direnişe, Batı Cephesi Yunan ilerleyişine karşı mücadeleyle öne çıkar.", "Cephe → düşman → komutan/anlaşma → sonuç şeklinde tablo kur.", "Düzenli ordunun esas mücadelesinin Batı Cephesi'nde olduğunu unutma."),
    "TBMM'nin Açılışı ve İç İsyanlar": konu("TBMM'nin açılışını, yetkilerini ve iç isyanlara karşı aldığı önlemleri öğren.", "23 Nisan 1920'de açılan TBMM yasama ve yürütme yetkilerini meclis hükümeti anlayışıyla kullanmıştır.", "İsyan nedenlerini, alınan hukuki ve askeri önlemleri ve sonuçlarını eşleştir.", "TBMM'nin açılışını Cumhuriyet'in ilanıyla aynı olay sanma; iki tarih ve amaç farklıdır."),
    "Atatürk İlkeleri": konu("Atatürk'ün Cumhuriyetçilik, Milliyetçilik, Halkçılık, Devletçilik, Laiklik ve İnkılapçılık ilkelerini öğren.", "Her ilkenin temel anlamını ve hangi uygulamalarla ilişkili olduğunu bil.", "Bir inkılabı gördüğünde hangi ilke veya ilkelerle bağlantılı olduğunu gerekçelendir.", "Bir inkılap yalnızca tek bir ilkeyle ilişkili olmak zorunda değildir; baskın bağlantıyı soruya göre seç."),
    "Atatürk İnkılapları": konu("Siyasi, hukuk, eğitim, toplumsal ve ekonomik inkılapları kronolojik ve amaçlarıyla öğren.", "Saltanatın kaldırılması, Cumhuriyet, halifeliğin kaldırılması, Tevhid-i Tedrisat, hukuk ve harf inkılabı temel başlıklardır.", "İnkılapları alanlarına ayır ve her birinin hangi ihtiyaca cevap verdiğini öğren.", "Saltanat ve halifeliğin kaldırılmasının aynı tarih olmadığını unutma."),
    "Atatürk Dönemi Türk Dış Politikası": konu("Atatürk döneminde Türkiye'nin komşular ve büyük devletlerle ilişkilerini öğren.", "Musul, Hatay, nüfus mübadelesi, Montrö ve bölgesel iş birlikleri önemli başlıklardır.", "Sorun → çözüm → antlaşma/karar şeklinde çalış.", "Lozan'da çözülemeyen Musul meselesi ile daha sonraki çözümü birbirine karıştırma."),
    "İnkılap Tarihi Genel Tekrar": konu("Milli Mücadele ve Cumhuriyet döneminin ana kronolojisini bir bütün olarak tekrar et.", "Mondros'tan Lozan'a, Cumhuriyet'in ilanından Atatürk dönemi dış politikasına kadar ana dönüm noktalarını sırala.", "Kronoloji + kişi + belge + sonuç dörtlüsüyle hızlı tekrar yap.", "Tarihleri ezberlerken olayın neden ve sonucunu bilmeden yalnızca rakama güvenme.")
  };

  const C = {
    "Doğa ve İnsan": konu("Coğrafyanın doğa ile insan arasındaki karşılıklı ilişkiyi incelemesini öğren.", "Fiziki ve beşeri unsurların ayrımını yap; insanın çevreyi değiştirdiği ve çevrenin insanı etkilediği örnekleri bil.", "Bir olayı görünce doğal mı beşeri mi olduğunu ve iki yönlü etkiyi sorgula.", "Coğrafyayı sadece yer şekilleri olarak düşünme; nüfus, ekonomi ve kültür de coğrafyanın konusudur."),
    "Dünya'nın Şekli ve Hareketleri": konu("Dünya'nın şekli ve günlük/yıllık hareketlerinin sonuçlarını öğren.", "Geoit şekil, eksen eğikliği, günlük hareket ve yıllık hareket temel kavramlardır.", "Gece-gündüz, mevsimler, gölge boyu ve sıcaklık farklarını hareketlerle eşleştir.", "Mevsimlerin temel nedeninin Dünya'nın Güneş'e uzaklığı olduğunu sanma; eksen eğikliği ve yıllık hareket belirleyicidir."),
    "Coğrafi Konum": konu("Matematik ve özel konumun sonuçlarını öğren.", "Enlem ve boylam matematik konumu; denizlere, kıtalara ve komşulara göre konum özel konumu ifade eder.", "Bir sonucun enlemden mi boylamdan mı özel konumdan mı kaynaklandığını belirle.", "Yerel saat farkını enlemle değil boylamla ilişkilendir."),
    "İklim Bilgisi": konu("İklim elemanlarını ve iklimi etkileyen faktörleri öğren.", "Sıcaklık, basınç, rüzgar, nem ve yağış temel iklim elemanlarıdır.", "Sıcaklık dağılışında enlem, yükselti, kara-deniz ve akıntı gibi etkenleri birlikte değerlendir.", "Hava durumu ile iklimi aynı kavram sanma; biri kısa süreli, diğeri uzun dönemli özellik taşır."),
    "Türkiye'nin İklimi": konu("Türkiye'deki iklim tiplerini ve bölgesel özelliklerini öğren.", "Karadeniz, Akdeniz ve karasal iklimin sıcaklık-yağış özelliklerini ayırt et.", "İklimi bitki örtüsü, tarım ve yerleşme özellikleriyle birlikte eşleştir.", "Türkiye'nin her yerinde dört mevsimin aynı özellikte yaşanmadığını unutma."),
    "Dünya'da Yerşekilleri": konu("Dünya'nın iç ve dış kuvvetlerinin oluşturduğu yer şekillerini öğren.", "Orojenez, epirojenez, volkanizma, deprem ve aşındırma-birikme temel süreçlerdir.", "Yer şeklini görünce hangi kuvvetin oluşturduğunu ve hangi kayaç/iklim ortamıyla ilişkili olduğunu düşün.", "İç kuvvetleri yalnızca deprem sanma; dağ oluşumu ve volkanizma da iç kuvvetlerle ilişkilidir."),
    "Türkiye'nin Yerşekilleri": konu("Türkiye'nin dağ, ova, plato ve kıyı özelliklerini öğren.", "Türkiye genç oluşumlu ve engebeli bir ülkedir; dağların uzanışı iklim ve ulaşımı etkiler.", "Dağların uzanışını kıyı, ulaşım ve yağış özellikleriyle birlikte harita üzerinde düşün.", "Dağların doğu-batı veya kuzey-güney uzanışının her bölgede aynı olmadığını unutma."),
    "Nüfus ve Yerleşme": konu("Nüfusun dağılışını ve yerleşmeyi etkileyen doğal-beşeri faktörleri öğren.", "Su, iklim, yer şekilleri, tarım, sanayi ve ulaşım nüfus dağılışını etkiler.", "Yoğun veya seyrek nüfuslu alanı açıklarken en az bir doğal ve bir beşeri faktör ara.", "Nüfus miktarı ile nüfus yoğunluğunu karıştırma."),
    "Türkiye'de Nüfus": konu("Türkiye'nin nüfus özelliklerini ve nüfus dağılışını öğren.", "Nüfusun kıyı, sanayi ve büyük şehirlerde yoğunlaşması; doğu ve iç kesimlerde bazı alanların seyrekliği temel örneklerdir.", "Nüfus piramidi, yoğunluk ve şehirleşme verilerini birlikte yorumla.", "En kalabalık yer ile en yoğun yer kavramlarını karıştırma."),
    "Göç": konu("Göç türlerini, nedenlerini ve sonuçlarını öğren.", "İç-dış, gönüllü-zorunlu ve mevsimlik-sürekli göç ayrımlarını bil.", "Göçü neden ve sonuçlarıyla ekonomik, sosyal ve demografik olarak sınıflandır.", "Göçün yalnızca ekonomik nedenli olduğunu düşünme; eğitim, güvenlik ve doğal afetler de etkili olabilir."),
    "Ekonomik Faaliyetler": konu("Birincil, ikincil, üçüncül ve diğer ekonomik faaliyetleri ayırt et.", "Tarım-hayvancılık birincil; sanayi ikincil; ticaret, ulaşım ve hizmetler üçüncül faaliyetlerdir.", "Mesleği doğrudan üretim mi işleme mi hizmet mi diye sınıflandır.", "Ham madde çıkarma ile sanayi üretimini aynı faaliyet olarak değerlendirme."),
    "Tarım - Hayvancılık - Madencilik": konu("Türkiye'nin tarım, hayvancılık ve maden kaynaklarının dağılışını öğren.", "İklim ve toprak tarımı; mera ve yem hayvancılığı; jeolojik yapı madenciliği etkiler.", "Ürün veya maden sorusunda önce doğal koşulu, sonra bölgeyi eşleştir.", "Bir tarım ürününün en çok üretildiği yer ile yetişebildiği her yer aynı değildir."),
    "Sanayi": konu("Sanayinin kuruluşunda ham madde, enerji, pazar, iş gücü ve ulaşımın rolünü öğren.", "Sanayi kuruluşlarının yeri tek bir faktörle değil birkaç faktörün birleşimiyle açıklanır.", "Fabrika türünü görünce ham maddeye mi, enerjiye mi, pazara mı daha bağımlı olduğunu düşün.", "Sanayileşmeyi yalnızca nüfus fazlalığıyla açıklama."),
    "Ulaşım ve Ticaret": konu("Ulaşım ağlarının ve ticaretin coğrafi dağılışını öğren.", "Ulaşım; yer şekilleri, nüfus, ekonomik faaliyetler ve geçitlerle ilişkilidir.", "Bir ulaşım güzergahının nedenini topoğrafya ve ekonomik merkezlerle açıklamaya çalış.", "En kısa yolun her zaman en uygun ulaşım yolu olduğunu varsayma."),
    "Türkiye'nin Bölgeleri": konu("Türkiye'nin coğrafi bölgelerini doğal ve beşeri özellikleriyle ayırt et.", "Bölgeler yer şekilleri, iklim, tarım, nüfus ve ekonomik faaliyetlerde farklı özelliklere sahiptir.", "Her bölge için üç güçlü ipucu belirle ve soruda ipuçlarını eşleştir.", "Coğrafi bölge ile idari bölgeyi aynı kavram sanma."),
    "Çevre ve Toplum": konu("İnsan faaliyetlerinin çevre üzerindeki etkilerini ve sürdürülebilirliği öğren.", "Kirlilik, erozyon, ormansızlaşma, su sorunları ve doğal afetlerin toplumla ilişkisini bil.", "Çevre sorusunda neden → sonuç → çözüm zinciri kur.", "Çevre sorunlarının tamamını yalnızca doğal nedenlerle açıklama; insan faaliyetleri önemli bir etkendir.")
  };

  const V = {
    "Hukukun Temel Kavramları": konu("Hukuk, hak, kişi, yaptırım ve kamu-özel hukuk ayrımlarını öğren.", "Hukuk kurallarının yaptırımı devlet gücüyle desteklenir; kamu hukuku devletin kamu gücüyle ilişkilerini düzenler.", "Bir hukuk dalını gördüğünde tarafların konumunu ve ilişkinin kamu gücü içerip içermediğini sorgula.", "Ahlak ve din kurallarının yaptırımını hukuk yaptırımıyla aynı sanma."),
    "Devlet Şekilleri": konu("Devletin siyasi yapısını ve egemenliğin kullanım biçimlerini öğren.", "Monarşi, oligarşi, teokrasi ve cumhuriyet gibi yönetim biçimlerini temel özellikleriyle ayırt et.", "Soruda egemenliğin kimde olduğunu ve yöneticinin nasıl belirlendiğini bul.", "Devlet şekli ile hükümet sistemini aynı kavram olarak değerlendirme."),
    "Türk Anayasa Hareketleri": konu("Osmanlı'dan Cumhuriyet'e anayasal gelişmeleri kronolojik öğren.", "Kanun-i Esasi, I. ve II. Meşrutiyet ile Cumhuriyet anayasaları anayasal gelişim zincirinin parçalarıdır.", "Anayasaları tarih ve getirdiği temel yeniliklerle eşleştir.", "İlk anayasa ile ilk Cumhuriyet anayasasını karıştırma."),
    "1982 Anayasası Genel Esasları": konu("1982 Anayasası'nın devletin temel niteliklerini ve anayasal esasları öğren.", "Türkiye Cumhuriyeti'nin insan haklarına saygılı, demokratik, laik ve sosyal bir hukuk devleti olduğu temel esaslardandır.", "Anayasanın başlangıç, değiştirilemez maddeler ve devletin temel niteliklerini ayrı başlıklarda çalış.", "Anayasa maddelerindeki değiştirilemez hükümleri sıradan yasa hükmü gibi değerlendirme."),
    "Yasama (TBMM)": konu("TBMM'nin oluşumu, görevleri ve yasama sürecinin temelini öğren.", "TBMM 600 milletvekilinden oluşur; kanun yapma, bütçe ve denetim gibi görevleri vardır.", "Görevleri yasama, denetim ve bütçe başlıklarında grupla.", "Kanun teklif etme ile kanun çıkarma süreçlerini birbirine karıştırma."),
    "Yürütme": konu("Yürütme yetkisinin Cumhurbaşkanı tarafından kullanılmasını ve yürütme işlemlerini öğren.", "Cumhurbaşkanlığı hükümet sisteminde yürütme yetkisi Cumhurbaşkanına aittir.", "Yürütme görevi, düzenleyici işlemler ve kamu yönetimi ilişkisini birlikte düşün.", "Yürütme ile yasamanın görevlerini birbirine karıştırma."),
    "Cumhurbaşkanı": konu("Cumhurbaşkanının seçimi, görevleri ve yetkilerinin temel çerçevesini öğren.", "Cumhurbaşkanı devletin başıdır ve yürütme yetkisine ilişkin anayasal görevleri vardır.", "Görevleri atama, temsil, yürütme ve anayasal yetki başlıklarında sınıflandır.", "Anayasadaki güncel değişiklikleri eski sistem bilgileriyle karıştırma."),
    "Bakanlıklar": konu("Bakanlıkların yürütme teşkilatındaki rolünü ve görev alanlarını öğren.", "Bakanlıklar kamu hizmetlerinin belirli alanlarda yürütülmesini sağlar ve Cumhurbaşkanlığı sisteminde yürütme teşkilatının parçasıdır.", "Bakanlık adı ile görev alanını eşleştir.", "Bağlı kuruluş ile bakanlığı aynı idari birim sanma."),
    "Yargı": konu("Yargı yetkisinin bağımsız ve tarafsız mahkemelerce kullanılmasını ve yargı kollarını öğren.", "Adli ve idari yargı başta olmak üzere görev alanlarını temel düzeyde ayırt et.", "Bir uyuşmazlığın özel kişiler arasında mı yoksa idareyle mi ilgili olduğuna bak.", "Yargı bağımsızlığı ile mahkemenin her kararının doğru olması kavramlarını karıştırma."),
    "Anayasa Mahkemesi": konu("Anayasa Mahkemesinin temel görev ve yetkilerini öğren.", "Anayasa uygunluk denetimi ve bireysel başvuru AYM'nin önemli görevlerindendir.", "AYM'nin hangi başvuruyu hangi amaçla incelediğini diğer yüksek mahkemelerden ayır.", "AYM'yi temyiz mahkemesi gibi düşünme; görev alanı anayasal çerçevededir."),
    "Yerel Yönetimler": konu("Mahalli idarelerin yapısını ve görev alanını öğren.", "İl özel idaresi, belediye ve köy yerel yönetim birimleri arasında temel ayrım yapılır.", "Yerel hizmetleri merkezi idare görevlerinden ayır; seçim ve organ yapılarını eşleştir.", "Yerel yönetimleri merkezi yönetimin taşra teşkilatıyla karıştırma."),
    "Temel Hak ve Özgürlükler": konu("Kişisel, sosyal-ekonomik ve siyasi hakların temel çerçevesini öğren.", "Hakların sınırlandırılması, hukuk devleti ve temel hakların korunması anayasal düzenin önemli parçalarıdır.", "Bir hakkın hangi kategoriye girdiğini ve hangi koşullarda sınırlanabileceğini anayasal çerçevede düşün.", "Her hakkın sınırsız olduğunu düşünme; sınırlama şartları anayasal kurallara bağlıdır."),
    "Uluslararası Kuruluşlar (BM, AB, NATO vb.)": konu("Başlıca uluslararası kuruluşların amaçlarını ve Türkiye ile ilişkilerini öğren.", "BM barış ve uluslararası iş birliği, NATO ortak savunma, AB ekonomik-siyasi bütünleşme hedefleriyle öne çıkar.", "Kuruluşu amaç ve merkez/üyelik gibi ayırt edici özellikleriyle eşleştir.", "Kuruluşların amaçlarını birbirine karıştırma; NATO ile BM aynı işlevde değildir.")
  };

  const G = {
    "Türkiye Gündemi": konu("Sınav dönemindeki Türkiye'de öne çıkan kurum, proje, kültür ve kamu gelişmelerini takip etmeyi öğren.", "Güncel bilgiler hızla değişebildiği için olayın tarihi, kurumu ve temel sonucunu kaydet.", "Her güncel bilgiyi 'ne oldu, nerede, kim/kurum, ne zaman?' dört sorusuyla özetle.", "Eski yılın güncel bilgisini yeni sınav yılına taşımadan önce tarihi kontrol et."),
    "Dünya Gündemi": konu("Dünyadaki önemli siyasi, bilimsel ve diplomatik gelişmeleri takip et.", "Büyük zirveler, uluslararası anlaşmalar, seçimler ve önemli küresel olaylar güncel bilgi kaynağıdır.", "Olayı ülke, kurum, tarih ve sonuç şeklinde dört parçaya ayır.", "Haber başlığını bilgi sanma; resmi kurum veya güvenilir kaynaktan doğrula."),
    "Ekonomi Gündemi": konu("Enflasyon, faiz, büyüme ve ekonomik kurumlarla ilgili güncel gelişmeleri takip et.", "TCMB, TÜİK ve önemli ekonomik göstergelerin neyi ölçtüğünü bil.", "Rakamı ezberlemekten önce göstergenin ne anlama geldiğini öğren; sınav öncesi rakamı güncelle.", "Değişken ekonomik verileri eski bir kaynaktan ezberleme."),
    "Bilim ve Teknoloji": konu("Bilim, uzay, yapay zeka ve Türkiye'nin teknoloji projelerindeki güncel gelişmeleri öğren.", "Önemli projelerin adı, amacı, kurumu ve tarihini temel düzeyde bil.", "Proje → kurum → amaç → önemli tarih şeklinde kartlar oluştur.", "Proje adı ile projeyi gerçekleştiren kurumu karıştırma."),
    "Kültür - Sanat": konu("Önemli kültür, sanat, edebiyat ve miras gelişmelerini takip et.", "UNESCO, büyük ödüller, sergiler, festivaller ve önemli sanat olayları güncel başlıklardır.", "Kişi/eser/ödül/kurum eşleştirmesi yap.", "Ödülün yılını ve kategorisini karıştırmamak için güncel kaynağı kontrol et."),
    "Spor": konu("Sınav döneminde öne çıkan milli takım, olimpiyat, dünya ve Avrupa organizasyonlarını takip et.", "Organizasyon adı, ev sahibi, Türkiye'nin derecesi ve önemli sporcular temel bilgilerdir.", "Spor dalı → organizasyon → derece → yıl şeklinde kısa not tut.", "Turnuva yılı ile ev sahipliği yılını karıştırma."),
    "Ödüller": konu("Nobel ve diğer önemli ulusal/uluslararası ödüllerin güncel sahiplerini takip et.", "Ödülün adı, kategori, kazanan ve gerekçe temel bilgi setidir.", "Ödülleri kategori ve yıl bazında kartlara ayır.", "Bir kişinin birden fazla ödülü veya farklı kategorisi olabileceğini unutma."),
    "Önemli Kurumlar": konu("Türkiye'deki önemli kamu kurumlarının görevlerini ve kısaltmalarını öğren.", "TÜİK, TÜBİTAK, RTÜK, BDDK, SPK gibi kurumların temel görevlerini ayırt et.", "Kurum → görev → bağlılık/ilişki şeklinde eşleştirme yap.", "Kurumun adı ile görev alanını sadece kısaltmadan tahmin etmeye çalışma."),
    "Uluslararası Gelişmeler": konu("Uluslararası zirve, anlaşma ve teşkilatların güncel gelişmelerini takip et.", "G20, D-8, Türk Devletleri Teşkilatı, BM ve NATO gibi yapıların temel amaçlarını bil.", "Zirve → ev sahibi → tarih → alınan önemli karar şeklinde not tut.", "Kuruluşun kuruluş tarihi ile güncel zirve tarihini karıştırma."),
    "Devlet Kurumları ile İlgili Gelişmeler": konu("Kamu kurumlarında görev, yapı veya mevzuat açısından önemli güncel değişimleri takip et.", "Yeni kurum, yeniden yapılandırma ve önemli kamu projeleri güncel bilgi kapsamına girebilir.", "Değişiklikten önceki ve sonraki yapıyı kısa bir karşılaştırmayla öğren.", "Güncel kurum bilgisini eski mevzuat bilgisiyle karıştırma; tarih kontrolü yap.")
  };

  // Mevcut ayrıntılı Türkçe içerikleri koru, diğer bütün konuları tamamla.
  Object.assign(DERS_OGRETIM, M, T, C, V, G);

  // Hiçbir seed konusu boş kalmasın. Yeni konu eklenirse de öğretim ekranı yine çalışsın.
  if (typeof TOPICS_SEED !== "undefined") {
    Object.values(TOPICS_SEED).flat().forEach((ad) => {
      if (!DERS_OGRETIM[ad]) {
        DERS_OGRETIM[ad] = konu(
          `${ad} konusunun temel kavramlarını ve KPSS'de soru çözmek için gerekli çerçeveyi öğren.`,
          `${ad} için önce ana kavramları, tanımları ve temel ilişkileri öğren. Bilmediğin terimleri kendi cümlelerinle tekrar et.`,
          `Sorularda verilen bilgiyi ${ad} konusundaki temel kuralla eşleştir. Önce konuyu sınıflandır, sonra işlem veya yorum adımına geç.`,
          `Seçeneklerde konuya yakın görünen ama kapsamı yanlış olan ifadeleri dikkatle ele. Güncel mevzuat veya değişken bilgi varsa sınav yılına göre doğrula.`
        );
      }
    });
  }
})();
