/* Final runtime layer: deterministic behavior fixes. */
(function(){'use strict';
let focus={active:false,remaining:0,total:0,last:0,interval:null,topic:null};
const pad=n=>String(Math.max(0,Math.floor(n))).padStart(2,'0'),fmt=s=>`${pad(Math.floor(s/60))}:${pad(s%60)}`;
function stop(){if(focus.interval){clearInterval(focus.interval);focus.interval=null}focus.active=false}
function render(){const t=document.querySelector('#runtimeFocusTimer');if(t)t.textContent=fmt(focus.remaining);const b=document.querySelector('#runtimeFocusBar');if(b)b.style.width=`${Math.max(0,100-focus.remaining/focus.total*100)}%`;const s=document.querySelector('#runtimeFocusState');if(s)s.textContent=focus.active?'Çalışıyor':'Duraklatıldı';const btn=document.querySelector('#runtimeFocusToggle');if(btn)btn.textContent=focus.active?'⏸ Duraklat':'▶ Başlat'}
function finish(){stop();const elapsed=Math.max(0,Math.floor((focus.total-focus.remaining)/60));if(elapsed&&focus.topic){const k=typeof studyKonuBul==='function'?studyKonuBul(focus.topic.dersId,focus.topic.id):null;if(k)k.calismaDk=(k.calismaDk||0)+elapsed;const g=typeof gunlukKayitAl==='function'?gunlukKayitAl():null;if(g)g.calismaDk=(g.calismaDk||0)+elapsed;if(typeof stateKaydet==='function')stateKaydet()}modalKapat();toast(elapsed?`⏱️ ${elapsed} dakikalık odak oturumu kaydedildi.`:'Oturum bitirildi.');if(typeof renderCalisma==='function'&&document.querySelector('#page-calisma.active'))renderCalisma()}
function tick(){if(!focus.active)return;const now=Date.now(),elapsed=Math.floor((now-focus.last)/1000);if(elapsed<1)return;focus.last+=elapsed*1000;focus.remaining=Math.max(0,focus.remaining-elapsed);render();if(focus.remaining<=0)finish()}
function openFocus(){stop();const topics=typeof calismaKonulariniGetir==='function'?calismaKonulariniGetir().filter(k=>k.durum!=='tamamlandi'):[],topic=topics[0]||null,mins=Math.max(5,Number(STATE?.ayarlar?.pomodoroCalismaDk)||25);focus={active:false,remaining:mins*60,total:mins*60,last:0,interval:null,topic};modalAc('⏱️ Odak Oturumu',`<div class="runtime-focus"><div class="runtime-focus-label">ODAK OTURUMU</div><div id="runtimeFocusTimer" class="runtime-focus-timer">${fmt(focus.remaining)}</div><div class="runtime-focus-topic">${topic?`📖 ${String(topic.ad).replace(/[<>]/g,'')}`:'📚 Serbest çalışma'}</div><div class="runtime-focus-state" id="runtimeFocusState">Hazır</div><div class="runtime-focus-track"><i id="runtimeFocusBar"></i></div><p class="alt">Sayaç gerçek geçen zamana göre ilerler; sekme yavaşlasa bile süre şaşmaz.</p></div>`,'<button type="button" class="btn btn-outline" id="runtimeFocusFinish">Bitir</button><button type="button" class="btn btn-primary" id="runtimeFocusToggle">▶ Başlat</button>');document.querySelector('#runtimeFocusToggle').onclick=()=>{if(focus.active)stop();else{focus.active=true;focus.last=Date.now();focus.interval=setInterval(tick,250)}render()};document.querySelector('#runtimeFocusFinish').onclick=finish;render()}
async function quickTest(){if(typeof apiSoruUret!=='function')return toast('Soru servisi yüklenemedi.');modalAc('⏳ Akıllı Test',`<div style="text-align:center;padding:25px"><strong>10 soru hazırlanıyor…</strong><p class="alt">Sorular gerçek AI servisi üzerinden oluşturuluyor.</p></div>`);try{const subject=typeof SUBJECTS_META!=='undefined'&&SUBJECTS_META[0]?SUBJECTS_META[0].name:'Türkçe';const r=await apiSoruUret({subject,topic:'Karışık',difficulty:'orta',count:10});if(!r.ok)throw new Error(r.mesaj||'Test oluşturulamadı.');const qs=r.veri?.sorular||[];if(qs.length!==10)throw new Error(`Sunucu ${qs.length} soru döndürdü; 10 gerekli.`);modalKapat();testModalBaslat(qs,'🎯 10 Soruluk Hızlı Test');}catch(e){modalAc('Test oluşturulamadı',`<p>${String(e.message||e).replace(/[<>]/g,'')}</p><p class="alt">İstek başarısızsa tekrar dene ile yeniden oluşturabilirsin.</p>`,'<button type="button" class="btn btn-accent" id="runtimeRetry">↻ Tekrar Dene</button><button type="button" class="btn btn-outline" id="runtimeClose">Kapat</button>');document.querySelector('#runtimeRetry').onclick=quickTest;document.querySelector('#runtimeClose').onclick=modalKapat}}
window.kpssOdakOturumuAc=openFocus;
function removeLegacy(){document.querySelectorAll('#premiumCerosBtn,.premium-testbar').forEach(x=>x.remove());const home=document.querySelector('#page-anasayfa');if(home){home.querySelectorAll('*').forEach(el=>{if(el.children.length===0&&/Özel Sürpriz/.test(el.textContent||''))(el.closest('.premium-actions')||el).remove()});const q=home.querySelector('#anaSoruCozBtn');if(q)q.textContent='🎯 Soru Çözmeye Başla'}}
let restoreY=0;document.addEventListener('change',e=>{const t=e.target;if(!t||!['studyDers','studyDurum'].includes(t.id))return;restoreY=window.scrollY;setTimeout(()=>window.scrollTo(0,restoreY),0);setTimeout(()=>window.scrollTo(0,restoreY),50)},true);
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const text=(b.textContent||'').trim().toLocaleLowerCase('tr-TR');if(text.includes('odak oturumunu başlat')){e.preventDefault();e.stopImmediatePropagation();openFocus();return}if(b.id==='anaSoruCozBtn'){e.preventDefault();e.stopImmediatePropagation();quickTest();return}},true);
new MutationObserver(removeLegacy).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',removeLegacy);else removeLegacy();
})();
