/* KPSS 2026 — Son güvenilirlik katmanı. Mevcut sayfaları değiştirmeden tekrarları,
   API zaman aşımını, AI sohbetini ve akıllı test akışını sağlamlaştırır. */
(function(){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const removeBeforeRender=sel=>document.querySelectorAll(sel).forEach(el=>el.remove());

  window.apiSoruUret=async function({subject,topic,difficulty,count}){return apiIstek('/api/ai/generate-questions',{method:'POST',body:{subject,topic,difficulty,count},timeoutMs:Math.min(10*60*1000,Math.max(90000,Number(count||10)*12000))});};
  window.apiAiOgretmenSor=async function(soru){return apiIstek('/api/ai/teacher',{method:'POST',body:{soru},timeoutMs:90000});};
  window.apiGuncelBilgilerGetir=async function(){return apiIstek('/api/current-affairs/today?refresh=1',{timeoutMs:120000});};

  let aiBusy=false;
  window.renderAiOgretmen=function(){
    const root=document.querySelector('#page-aiogretmen');if(!root)return;
    root.innerHTML=`<div class="page-head"><h1>AI Öğretmen</h1><div class="alt">KPSS konularını sor, adım adım öğren. Cevap gelmezse tekrar deneyebilirsin.</div></div><div class="card card-pad" style="margin-bottom:14px"><div style="display:flex;gap:8px;flex-wrap:wrap"><input type="file" id="aiFotoInput" accept="image/*" capture="environment" hidden><button type="button" class="btn btn-sm" id="aiFotoBtn">📸 Fotoğraftan Soru Çöz</button><button type="button" class="btn btn-sm btn-outline" id="aiTemizleBtn">Sohbeti Temizle</button></div></div><div id="aiSohbetKutu" class="ai-sohbet-kutu"></div><div class="ai-giris-satiri" style="display:flex;gap:8px;margin-top:10px"><input type="text" id="aiSoruInput" placeholder="Örn: Saltanat hangi tarihte kaldırıldı?" style="flex:1"><button type="button" class="btn btn-accent" id="aiGonderBtn">Gönder</button></div>`;
    draw();
    const send=()=>aiSend();document.querySelector('#aiGonderBtn').onclick=send;document.querySelector('#aiSoruInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send();}};document.querySelector('#aiFotoBtn').onclick=()=>document.querySelector('#aiFotoInput').click();document.querySelector('#aiFotoInput').onchange=aiPhoto;document.querySelector('#aiTemizleBtn').onclick=()=>{aiSohbetGecmisi=[];draw();};
  };
  function draw(){const box=document.querySelector('#aiSohbetKutu');if(!box)return;if(!aiSohbetGecmisi.length){box.innerHTML='<div class="alt" style="padding:22px 0">Henüz soru yok. Bir konu sorarak başlayabilirsin.</div>';return;}box.innerHTML=aiSohbetGecmisi.map(m=>`<div class="ai-msj ${m.rol==='kullanici'?'ai-msj-kullanici':'ai-msj-bot'}">${m.loading?'<span>⏳ Düşünüyor…</span>':m.error?`<div>${esc(m.metin)}</div><button type="button" class="btn btn-sm btn-outline" data-ai-retry="1">↻ Tekrar dene</button>`:m.metin}</div>`).join('');box.scrollTop=box.scrollHeight;box.querySelector('[data-ai-retry]')?.addEventListener('click',()=>{const last=[...aiSohbetGecmisi].reverse().find(x=>x.rol==='kullanici');if(last)aiSend(last.raw||last.metin);});}
  async function aiSend(forceText){if(aiBusy)return;const input=document.querySelector('#aiSoruInput');const soru=String(forceText??input?.value??'').trim();if(!soru)return;aiBusy=true;if(input)input.value='';aiSohbetGecmisi.push({rol:'kullanici',metin:esc(soru),raw:soru},{rol:'bot',loading:true});draw();try{const r=await apiAiOgretmenSor(soru);aiSohbetGecmisi.pop();if(!r.ok)aiSohbetGecmisi.push({rol:'bot',error:true,metin:r.mesaj||'AI Öğretmen cevap veremedi.'});else aiSohbetGecmisi.push({rol:'bot',metin:esc(r.veri?.cevap||'AI Öğretmen boş cevap döndürdü.').replace(/\n/g,'<br>')});}catch(e){aiSohbetGecmisi.pop();aiSohbetGecmisi.push({rol:'bot',error:true,metin:'Bağlantı kurulamadı. Tekrar deneyebilirsin.'});}finally{aiBusy=false;draw();}}
  function aiPhoto(e){const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){toast('Fotoğraf 8 MB altında olmalı.');e.target.value='';return;}const r=new FileReader();r.onload=async()=>{aiBusy=true;aiSohbetGecmisi.push({rol:'kullanici',metin:'📸 Fotoğraf gönderildi.'},{rol:'bot',loading:true});draw();try{const out=await apiFotoCoz(r.result,f.type);aiSohbetGecmisi.pop();if(!out.ok)aiSohbetGecmisi.push({rol:'bot',error:true,metin:out.mesaj});else{const s=out.veri||{};aiSohbetGecmisi.push({rol:'bot',metin:`<strong>${esc(s.soru||'Soru')}</strong><br>${Object.entries(s.secenekler||{}).map(([h,v])=>`${h}) ${esc(v)}`).join('<br>')}<br><br><strong>Doğru cevap: ${esc(s.dogruCevap||'?')}</strong><br>${esc(s.aciklama||'')}`});}}catch(_){aiSohbetGecmisi.pop();aiSohbetGecmisi.push({rol:'bot',error:true,metin:'Fotoğraf çözülemedi. Daha net bir görsel deneyin.'});}finally{aiBusy=false;draw();}};r.readAsDataURL(f);e.target.value='';}

  function wrap(name,cleanup,after){const old=window[name];if(typeof old!=='function'||old.__stable)return;const fn=function(){cleanup();const r=old.apply(this,arguments);after&&after();return r};fn.__stable=true;window[name]=fn;}
  function homeAfter(){const b=document.querySelector('#anaSoruCozBtn');if(b)b.textContent='🎯 Soru Çözmeye Başla';document.querySelectorAll('#premiumCerosBtn').forEach(x=>x.remove());}
  function studyAfter(){}
  function testsAfter(){const root=document.querySelector('#page-denemeler');if(root&&!root.querySelector('#stableSmartTest')){const card=document.createElement('div');card.id='stableSmartTest';card.className='card card-pad';card.style.marginBottom='16px';card.innerHTML='<div class="section-title">⚡ Akıllı Test</div><p class="alt">10, 20 veya 40 soruluk gerçek AI testi oluştur.</p><div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><select id="stableTestCount" style="max-width:150px"><option value="10">10 soru</option><option value="20">20 soru</option><option value="40">40 soru</option></select><button type="button" class="btn btn-accent" id="stableTestGo">Soruları Getir</button></div>';root.prepend(card);card.querySelector('#stableTestGo').onclick=()=>smartTestStable(Number(card.querySelector('#stableTestCount').value));}}
  async function smartTestStable(count){if(!apiBaseUrlAl()){toast('Önce Ayarlar bölümünden backend adresini kaydet.');sayfaGec('ayarlar');return;}modalAc('⏳ Test hazırlanıyor',`<div style="text-align:center;padding:24px"><strong>${count} soru hazırlanıyor…</strong><p class="alt">Sorular parça parça üretiliyor. Pencereyi kapatma.</p><div class="progress-track"><div class="progress-fill" id="stableTestBar" style="width:5%"></div></div><div id="stableTestStatus" class="alt" style="margin-top:8px">AI ile bağlantı kuruluyor…</div></div>`,'');try{const subject=SUBJECTS_META[0]?.name||'Türkçe';const r=await apiSoruUret({subject,topic:'Karışık',difficulty:'orta',count});if(!r.ok)throw new Error(r.mesaj||'Test oluşturulamadı.');const qs=r.veri?.sorular||[];if(qs.length!==count)throw new Error(`Sunucu ${qs.length} soru döndürdü; ${count} gerekli.`);modalKapat();testModalBaslat(qs,`⚡ ${count} Soruluk Akıllı Test`);}catch(e){modalAc('Test oluşturulamadı',`<p>${esc(e.message||e)}</p><p class="alt">Sunucu cevap vermediyse birkaç dakika sonra tekrar deneyebilirsin.</p>`,'<button type="button" class="btn btn-accent" id="stableTestClose">Kapat</button>');document.querySelector('#stableTestClose').onclick=modalKapat;}}
  function initWraps(){wrap('renderAnaSayfa',()=>removeBeforeRender('.premium-hero,.premium-grid'),homeAfter);wrap('renderCalisma',()=>removeBeforeRender('.premium-study-tools,.focus-hub,.smart-study-grid'),studyAfter);wrap('renderDenemeler',()=>removeBeforeRender('.premium-testbar,#stableSmartTest'),testsAfter);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(initWraps,0));else setTimeout(initWraps,0);
})();
