/* KPSS 2026 — Son güvenilirlik katmanı. Mevcut sayfaları değiştirmeden tekrarları,
   API zaman aşımını, AI sohbetini ve akıllı test akışını sağlamlaştırır. */
(function(){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const removeBeforeRender=sel=>document.querySelectorAll(sel).forEach(el=>el.remove());

  window.apiSoruUret=async function({subject,topic,difficulty,count}){return apiIstek('/api/ai/generate-questions',{method:'POST',body:{subject,topic,difficulty,count},timeoutMs:Math.min(10*60*1000,Math.max(90000,Number(count||10)*12000))});};

  function wrap(name,cleanup,after){const old=window[name];if(typeof old!=='function'||old.__stable)return;const fn=function(){cleanup();const r=old.apply(this,arguments);after&&after();return r};fn.__stable=true;window[name]=fn;}
  function homeAfter(){const b=document.querySelector('#anaSoruCozBtn');if(b)b.textContent='🎯 Soru Çözmeye Başla';document.querySelectorAll('#premiumCerosBtn').forEach(x=>x.remove());}
  function studyAfter(){}
  function testsAfter(){const root=document.querySelector('#page-denemeler');if(root&&!root.querySelector('#stableSmartTest')){const card=document.createElement('div');card.id='stableSmartTest';card.className='card card-pad';card.style.marginBottom='16px';card.innerHTML='<div class="section-title">⚡ Akıllı Test</div><p class="alt">10, 20 veya 40 soruluk gerçek AI testi oluştur.</p><div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><select id="stableTestCount" style="max-width:150px"><option value="10">10 soru</option><option value="20">20 soru</option><option value="40">40 soru</option></select><button type="button" class="btn btn-accent" id="stableTestGo">Soruları Getir</button></div>';root.prepend(card);card.querySelector('#stableTestGo').onclick=()=>smartTestStable(Number(card.querySelector('#stableTestCount').value));}}
  async function smartTestStable(count){if(!apiBaseUrlAl()){toast('Önce Ayarlar bölümünden backend adresini kaydet.');sayfaGec('ayarlar');return;}modalAc('⏳ Test hazırlanıyor',`<div style="text-align:center;padding:24px"><strong>${count} soru hazırlanıyor…</strong><p class="alt">Sorular parça parça üretiliyor. Pencereyi kapatma.</p><div class="progress-track"><div class="progress-fill" id="stableTestBar" style="width:5%"></div></div><div id="stableTestStatus" class="alt" style="margin-top:8px">AI ile bağlantı kuruluyor…</div></div>`,'');try{const subject=SUBJECTS_META[0]?.name||'Türkçe';const r=await apiSoruUret({subject,topic:'Karışık',difficulty:'orta',count});if(!r.ok)throw new Error(r.mesaj||'Test oluşturulamadı.');const qs=r.veri?.sorular||[];if(qs.length!==count)throw new Error(`Sunucu ${qs.length} soru döndürdü; ${count} gerekli.`);modalKapat();testModalBaslat(qs,`⚡ ${count} Soruluk Akıllı Test`);}catch(e){modalAc('Test oluşturulamadı',`<p>${esc(e.message||e)}</p><p class="alt">Sunucu cevap vermediyse birkaç dakika sonra tekrar deneyebilirsin.</p>`,'<button type="button" class="btn btn-accent" id="stableTestClose">Kapat</button>');document.querySelector('#stableTestClose').onclick=modalKapat;}}
  function initWraps(){wrap('renderAnaSayfa',()=>removeBeforeRender('.premium-hero,.premium-grid'),homeAfter);wrap('renderCalisma',()=>removeBeforeRender('.premium-study-tools,.focus-hub,.smart-study-grid'),studyAfter);wrap('renderDenemeler',()=>removeBeforeRender('.premium-testbar,#stableSmartTest'),testsAfter);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(initWraps,0));else setTimeout(initWraps,0);
})();
