/* Central OpenRouter provider. Free model IDs are kept current and validated. */
const OPENROUTER_URL="https://openrouter.ai/api/v1/chat/completions";
const FREE_MODELS=["openai/gpt-oss-20b:free","inclusionai/ling-3.0-flash:free","nvidia/nemotron-3-ultra-550b-a55b:free"];
const ATTEMPT_TIMEOUT_MS=45000;
function getApiKey(){const key=String(process.env.OPENROUTER_API_KEY||"").trim();if(!key)throw new Error("OPENROUTER_API_KEY Railway Variables bölümünde tanımlı değil.");return key;}
function getModels(){const env=String(process.env.OPENROUTER_MODEL||"").trim();return env&&FREE_MODELS.includes(env)?[env,...FREE_MODELS.filter(x=>x!==env)]:[...FREE_MODELS];}
function timeoutError(){const e=new Error("AI isteği zaman aşımına uğradı.");e.code="AI_TIMEOUT";return e;}
async function request(body,timeoutMs=ATTEMPT_TIMEOUT_MS){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(OPENROUTER_URL,{method:"POST",headers:{Authorization:`Bearer ${getApiKey()}`,"Content-Type":"application/json","HTTP-Referer":process.env.APP_URL||"https://kpss-backend-production.up.railway.app","X-Title":"KPSS-2026"},body:JSON.stringify(body),signal:controller.signal});const text=await response.text();let data={};try{data=JSON.parse(text)}catch{}if(!response.ok)throw new Error(`OpenRouter API ${response.status}: ${data?.error?.message||text.slice(0,500)}`);return data;}catch(e){if(e?.name==="AbortError")throw timeoutError();throw e}finally{clearTimeout(timer);}}
function contentText(c){return Array.isArray(c)?c.map(x=>typeof x==="string"?x:(x?.text||"")).join(""):String(c||"");}
async function generate({system,prompt,jsonMode=false,maxTokens=2600}){let lastError=null;for(const model of getModels()){try{const messages=[];if(system)messages.push({role:"system",content:String(system)});messages.push({role:"user",content:String(prompt)});const base={model,messages,temperature:0.15,max_tokens:maxTokens};let data;try{data=await request(jsonMode?{...base,response_format:{type:"json_object"}}:base);}catch(err){if(jsonMode&&/response.?format|json_object|structured/i.test(err.message||""))data=await request(base);else throw err;}const content=contentText(data?.choices?.[0]?.message?.content);if(!content.trim())throw new Error("OpenRouter AI boş cevap döndürdü.");if(/^(User Safety|Safety)\s*:/i.test(content.trim()))throw new Error("Model güvenlik yönlendirmesi döndürdü.");console.log(`[AI Provider] başarılı model: ${model}`);return content;}catch(err){lastError=err;console.error(`[AI Provider] ${model} başarısız: ${err.message}`);}}throw lastError||new Error("Kullanılabilir ücretsiz AI modeli bulunamadı.");}
async function generateWithImage({system,prompt,imageBase64,mimeType="image/jpeg"}){if(!imageBase64)throw new Error("Görsel verisi gönderilmedi.");const models=["nvidia/nemotron-3-nano-omni:free","openrouter/free"];let last=null;for(const model of models){try{const messages=[];if(system)messages.push({role:"system",content:String(system)});messages.push({role:"user",content:[{type:"text",text:String(prompt)},{type:"image_url",image_url:{url:`data:${mimeType};base64,${imageBase64}`}}]});const data=await request({model,messages,temperature:0.1,max_tokens:2200,response_format:{type:"json_object"}},60000);const content=contentText(data?.choices?.[0]?.message?.content);if(!content.trim())throw new Error("Görsel AI boş cevap döndürdü.");return content;}catch(e){last=e;console.error(`[AI Provider] vision ${model} başarısız: ${e.message}`)}}throw last||new Error("Görsel AI kullanılamıyor.");}
module.exports={generate,generateWithImage,getModels};
