/* Central Gemini provider. Replaces OpenRouter for better reliability. */
const GEMINI_API_URL="https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent";
const DEFAULT_GEMINI_MODEL="gemini-3.6-flash";
const ATTEMPT_TIMEOUT_MS=45000;
function getApiKey(){const key=String(process.env.GEMINI_API_KEY||"").trim();if(!key)throw new Error("GEMINI_API_KEY Railway Variables bölümünde tanımlı değil.");return key;}
function getModel(){const env=String(process.env.GEMINI_MODEL||DEFAULT_GEMINI_MODEL).trim();return env||DEFAULT_GEMINI_MODEL;}
function timeoutError(){const e=new Error("AI isteği zaman aşımına uğradı.");e.code="AI_TIMEOUT";return e;}
async function request(messages,timeoutMs=ATTEMPT_TIMEOUT_MS){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const model=getModel();const url=GEMINI_API_URL.replace("{model}",model);const headers={"Content-Type":"application/json"};const body={contents:messages.map(m=>({role:m.role||"user",parts:[{text:m.content||m.prompt}]})),generationConfig:{maxOutputTokens:2600}};const response=await fetch(url,{method:"POST",headers,body:JSON.stringify(body),signal:controller.signal});const text=await response.text();let data={};try{data=JSON.parse(text)}catch{}if(!response.ok){const errText=text.slice(0,500);throw new Error(`Gemini API ${response.status}: ${data?.error?.message||errText}`);}return data;}catch(e){if(e?.name==="AbortError")throw timeoutError();throw e}finally{clearTimeout(timer);}}
function contentText(c){return Array.isArray(c)?c.map(x=>typeof x==="string"?x:(x?.text||"")).join(""):String(c||"");}
async function generate({system,prompt,jsonMode=false,maxTokens=2600}){let lastError=null;try{const messages=[];if(system)messages.push({role:"user",content:system});messages.push({role:"user",content:prompt});const data=await request(messages,ATTEMPT_TIMEOUT_MS);const content=data?.candidates?.[0]?.content?.parts?.[0]?.text;if(!content?.trim())throw new Error("Gemini AI boş cevap döndürdü.");console.log(`[Gemini Provider] başarılı model: ${getModel()}`);return content;}catch(err){lastError=err;console.error(`[Gemini Provider] başarısız: ${err.message}`);}throw lastError||new Error("Gemini AI isteği başarısız.");}
async function generateWithImage({system,prompt,imageBase64,mimeType="image/jpeg"}){if(!imageBase64)throw new Error("Görsel verisi gönderilmedi.");let last=null;try{const messages=[];if(system)messages.push({role:"user",content:system});messages.push({role:"user",content:[{type:"text",text:String(prompt)},{type:"inlineData",inlineData:{mimeType,data:imageBase64}}]});const data=await request(messages,60000);const content=data?.candidates?.[0]?.content?.parts?.[0]?.text;if(!content?.trim())throw new Error("Görsel AI boş cevap döndürdü.");return content;}catch(e){last=e;console.error(`[Gemini Provider] vision başarısız: ${e.message}`);}throw last||new Error("Görsel AI kullanılamıyor.");}
module.exports={generate,generateWithImage};
