const express=require("express");const {nanoid}=require("nanoid");const searchWeb=require("../services/webSearch").searchWeb;const {rssGuncelGetir}=require("../services/rssNews");const aiProvider=require("../services/aiProvider");const cache=require("../services/cache");const db=require("../db/db");const {CURRENT_AFFAIRS_CATEGORIES}=require("../config/sources");const {aiRateLimit}=require("../middleware/rateLimit");const router=express.Router();
function bugunISO(){return new Date().toISOString().slice(0,10)}
function guvenliJson(m){if(!m||typeof m!=="string")return null;let x=m.replace(/```json|```/g,"").trim();try{return JSON.parse(x)}catch{}const a=Math.min(...[x.indexOf("["),x.indexOf("{")].filter(i=>i>=0));if(!Number.isFinite(a))return null;const open=x[a],close=open==="["?"]":"}";let d=0,s=false,e=false;for(let i=a;i<x.length;i++){const c=x[i];if(e){e=false;continue}if(c==="\\"&&s){e=true;continue}if(c==='"'){s=!s;continue}if(s)continue;if(c===open)d++;if(c===close&&--d===0){try{return JSON.parse(x.slice(a,i+1))}catch{return null}}}return null;}
function tarihGecerliMi(t,maxGun=3){if(!t)return true;const d=new Date(t);return Number.isNaN(d.getTime())||(Date.now()-d.getTime())/86400000<=maxGun;}
function satirdanNesneyeCevir(s){const kaynaklar=db.prepare("SELECT title,url,domain FROM sources WHERE current_affairs_id=?").all(s.id);return{id:s.id,baslik:s.title,ozet:s.summary,kategori:s.category,tarih:s.published_at,kaynakAdi:s.source_name,kaynakUrl:s.source_url,tumKaynaklar:kaynaklar};}
async function kaynakBul(kategori,query){let rss=await rssGuncelGetir(kategori,8);rss=rss.filter(x=>tarihGecerliMi(x.tarih));if(rss.length)return rss;return (await searchWeb(query,{onlyTrusted:true,limit:5})).filter(x=>tarihGecerliMi(x.tarih));}
async function gununGuncelBilgileriniUret(force=false){const bugun=bugunISO(),key=`current-affairs:${bugun}`;if(!force){const c=cache.get(key);if(c?.length)return c;const rows=db.prepare("SELECT * FROM current_affairs WHERE published_at=? ORDER BY rowid DESC LIMIT 30").all(bugun);if(rows.length){const result=rows.map(satirdanNesneyeCevir);cache.set(key,result);return result;}}
  const mevcut=db.prepare("SELECT title FROM current_affairs WHERE published_at=?").all(bugun).map(x=>x.title);const kategoriler=[...CURRENT_AFFAIRS_CATEGORIES].sort(()=>Math.random()-0.5).slice(0,force?8:10);const uretilen=[];
  for(const kategori of kategoriler){try{const sorgu=kategori.sorgu.replace("%TARIH%",bugun);const kaynaklar=await kaynakBul(kategori.ad,sorgu);if(!kaynaklar.length)continue;const kaynakMetni=kaynaklar.map((k,i)=>`[${i+1}] ${k.baslik} (${k.kaynak}) — ${k.icerikOzeti||""}`).join("\n");const text=await aiProvider.generate({system:"KPSS güncel bilgi editörüsün. Yalnızca geçerli JSON ver.",prompt:`Kategori: ${kategori.ad}\nBugünün tarihi: ${bugun}\nAşağıdaki güncel RSS/web kaynaklarından 1 adet sınav açısından anlamlı bilgi kartı çıkar. Başlıkları mümkün olduğunca benzersiz seç.\n${kaynakMetni}\nÖnceden kullanılan başlıklar: ${mevcut.slice(-40).join(" | ")}\nFormat: [{"baslik":"...","ozet":"..."}]`,jsonMode:true,maxTokens:900});const parsed=guvenliJson(text)||[];const arr=Array.isArray(parsed)?parsed:(parsed.bilgiler||[]);for(const kart of arr){if(!kart?.baslik||!kart?.ozet||mevcut.includes(kart.baslik))continue;const src=kaynaklar[0],id=nanoid();db.prepare("INSERT INTO current_affairs (id,title,summary,category,published_at,source_name,source_url,content) VALUES (?,?,?,?,?,?,?,?)").run(id,kart.baslik,kart.ozet,kategori.ad,bugun,src.kaynak,src.url,kaynakMetni);for(const k of kaynaklar)db.prepare("INSERT INTO sources (id,current_affairs_id,title,url,domain) VALUES (?,?,?,?,?)").run(nanoid(),id,k.baslik,k.url,k.kaynak);uretilen.push({id,baslik:kart.baslik,ozet:kart.ozet,kategori:kategori.ad,tarih:bugun,kaynakAdi:src.kaynak,kaynakUrl:src.url});mevcut.push(kart.baslik);}}catch(e){console.error(`[current-affairs] ${kategori.ad}:`,e.message)}}
  const result=uretilen.length?uretilen:db.prepare("SELECT * FROM current_affairs WHERE published_at=? ORDER BY rowid DESC LIMIT 30").all(bugun).map(satirdanNesneyeCevir);cache.set(key,result);return result;}
router.get("/today",async(req,res)=>{try{const force=String(req.query.refresh||"")==="1";const bilgiler=await gununGuncelBilgileriniUret(force);res.json({tarih:bugunISO(),yenilendi:force,bilgiler,canli:kaynakBul?true:false});}catch(e){console.error("[current-affairs/today]",e.message);res.status(503).json({hata:"Güncel bilgi alınamadı. Kaynaklar geçici olarak yanıt vermiyor."});}});
router.post("/quiz",aiRateLimit,async(req,res)=>{try{const bilgiler=await gununGuncelBilgileriniUret(false);if(!bilgiler.length)return res.status(503).json({hata:"Bugün için yeterli güncel bilgi bulunamadı."});const bilgiMetni=bilgiler.slice(0,10).map((b,i)=>`${i+1}. [${b.kategori}] ${b.baslik}: ${b.ozet}`).join("\n");const text=await aiProvider.generate({system:"KPSS güncel bilgiler testi hazırlayan soru yazarısın. Yalnızca JSON ver.",prompt:`Aşağıdaki güncel bilgilerden 10 özgün çoktan seçmeli soru üret. A-E seçenekleri, tek doğru cevap ve kısa açıklama.\n${bilgiMetni}`,jsonMode:true,maxTokens:2600});const parsed=guvenliJson(text)||{};const sorular=Array.isArray(parsed)?parsed:(parsed.sorular||[]);res.json({tarih:bugunISO(),sorular});}catch(e){console.error("[current-affairs/quiz]",e.message);res.status(503).json({hata:"Bugünün testi oluşturulamadı. Lütfen tekrar deneyin."});}});module.exports=router;
